version: "#{build}"
image: Visual Studio 2017
configuration: Release

before_build:
- ps: dotnet restore
build:
  verbosity: minimal
test_script:
- ps: dotnet test test/Yargon.Parsing.Tests/Yargon.Parsing.Tests.csproj
